# Generated by Django 6.0.4 on 2026-04-09 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='courses',
        ),
    ]
